// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Context;

#nullable disable

namespace WebApi.Migrations.ProductDb
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.Entities.CategoryEntity", b =>
                {
                    b.Property<Guid>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = new Guid("7bce8f5a-6e92-4472-9168-eb4a8506c6bf"),
                            CategoryName = "men"
                        },
                        new
                        {
                            CategoryID = new Guid("e540be20-c17d-4e5a-aebd-0733c7955cdb"),
                            CategoryName = "woman"
                        },
                        new
                        {
                            CategoryID = new Guid("b39664eb-6934-4dcd-986e-7c6cf0efb8c9"),
                            CategoryName = "kid"
                        },
                        new
                        {
                            CategoryID = new Guid("1a421152-cf67-4eda-af8e-61e490f9dddd"),
                            CategoryName = "accessories"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Entities.CategoryTagEntity", b =>
                {
                    b.Property<Guid>("CategoryTagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductEntityProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoryTagID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ProductEntityProductID");

                    b.HasIndex("TagID");

                    b.ToTable("CategoryTags");

                    b.HasData(
                        new
                        {
                            CategoryTagID = new Guid("fb5d50c7-947e-4d1e-9a94-4c2d2678f3e8"),
                            CategoryID = new Guid("7bce8f5a-6e92-4472-9168-eb4a8506c6bf"),
                            TagID = new Guid("4a3914f7-deb4-4265-b869-57cc712f6896")
                        },
                        new
                        {
                            CategoryTagID = new Guid("26189f98-d2e9-46a1-9b7a-51970043b427"),
                            CategoryID = new Guid("7bce8f5a-6e92-4472-9168-eb4a8506c6bf"),
                            TagID = new Guid("971bbffb-1719-4e6e-89da-9ab5ab77a287")
                        },
                        new
                        {
                            CategoryTagID = new Guid("2e23e9ad-0a22-4eab-9468-4482fb9e9a28"),
                            CategoryID = new Guid("7bce8f5a-6e92-4472-9168-eb4a8506c6bf"),
                            TagID = new Guid("bafb4114-a474-42c4-8088-9b0002aae502")
                        },
                        new
                        {
                            CategoryTagID = new Guid("c2819ae8-f2dd-4333-8446-15b0917e8a7a"),
                            CategoryID = new Guid("7bce8f5a-6e92-4472-9168-eb4a8506c6bf"),
                            TagID = new Guid("8a6c018f-6b1c-4bca-beac-85dc2249748d")
                        },
                        new
                        {
                            CategoryTagID = new Guid("20272e49-d8f5-4c33-bd3b-c0fd5f2a8fec"),
                            CategoryID = new Guid("7bce8f5a-6e92-4472-9168-eb4a8506c6bf"),
                            TagID = new Guid("5f9499ee-8cdb-457a-b09d-95c5b84cb379")
                        },
                        new
                        {
                            CategoryTagID = new Guid("41049391-51e2-4752-8561-eeb75d1063e6"),
                            CategoryID = new Guid("e540be20-c17d-4e5a-aebd-0733c7955cdb"),
                            TagID = new Guid("4a3914f7-deb4-4265-b869-57cc712f6896")
                        },
                        new
                        {
                            CategoryTagID = new Guid("7102e504-165f-4d23-bcec-6778275808f1"),
                            CategoryID = new Guid("e540be20-c17d-4e5a-aebd-0733c7955cdb"),
                            TagID = new Guid("971bbffb-1719-4e6e-89da-9ab5ab77a287")
                        },
                        new
                        {
                            CategoryTagID = new Guid("3b93cb38-8122-41ee-9712-e68a59efcc68"),
                            CategoryID = new Guid("e540be20-c17d-4e5a-aebd-0733c7955cdb"),
                            TagID = new Guid("bafb4114-a474-42c4-8088-9b0002aae502")
                        },
                        new
                        {
                            CategoryTagID = new Guid("d85029ef-f1c3-4c20-a8ca-5b4ee839fa6b"),
                            CategoryID = new Guid("e540be20-c17d-4e5a-aebd-0733c7955cdb"),
                            TagID = new Guid("8a6c018f-6b1c-4bca-beac-85dc2249748d")
                        },
                        new
                        {
                            CategoryTagID = new Guid("751f383e-ce71-4425-aa5e-40bc5f521300"),
                            CategoryID = new Guid("e540be20-c17d-4e5a-aebd-0733c7955cdb"),
                            TagID = new Guid("5f9499ee-8cdb-457a-b09d-95c5b84cb379")
                        },
                        new
                        {
                            CategoryTagID = new Guid("ccd9bd4e-3703-4072-a520-edb937daf953"),
                            CategoryID = new Guid("e540be20-c17d-4e5a-aebd-0733c7955cdb"),
                            TagID = new Guid("42ce8eb8-ba9f-4708-aac8-e2f8159bf9d3")
                        },
                        new
                        {
                            CategoryTagID = new Guid("fadf2a9b-a0b4-4d37-ab99-e2127c946ead"),
                            CategoryID = new Guid("b39664eb-6934-4dcd-986e-7c6cf0efb8c9"),
                            TagID = new Guid("4a3914f7-deb4-4265-b869-57cc712f6896")
                        },
                        new
                        {
                            CategoryTagID = new Guid("51a8d026-0070-4471-9ead-2ab151095f00"),
                            CategoryID = new Guid("b39664eb-6934-4dcd-986e-7c6cf0efb8c9"),
                            TagID = new Guid("971bbffb-1719-4e6e-89da-9ab5ab77a287")
                        },
                        new
                        {
                            CategoryTagID = new Guid("4eac7f23-95e6-4f62-a9fa-a196ac95729b"),
                            CategoryID = new Guid("b39664eb-6934-4dcd-986e-7c6cf0efb8c9"),
                            TagID = new Guid("bafb4114-a474-42c4-8088-9b0002aae502")
                        },
                        new
                        {
                            CategoryTagID = new Guid("757f2207-38f7-4074-b77c-4a3dc5891e3d"),
                            CategoryID = new Guid("b39664eb-6934-4dcd-986e-7c6cf0efb8c9"),
                            TagID = new Guid("8a6c018f-6b1c-4bca-beac-85dc2249748d")
                        },
                        new
                        {
                            CategoryTagID = new Guid("b4e38b32-c0f8-444e-a670-d97912a1366c"),
                            CategoryID = new Guid("b39664eb-6934-4dcd-986e-7c6cf0efb8c9"),
                            TagID = new Guid("5f9499ee-8cdb-457a-b09d-95c5b84cb379")
                        },
                        new
                        {
                            CategoryTagID = new Guid("39a023d1-2a36-4fc5-9e0c-837a251986f5"),
                            CategoryID = new Guid("b39664eb-6934-4dcd-986e-7c6cf0efb8c9"),
                            TagID = new Guid("42ce8eb8-ba9f-4708-aac8-e2f8159bf9d3")
                        },
                        new
                        {
                            CategoryTagID = new Guid("948a4a2f-a2db-47ec-9925-6399b799ef34"),
                            CategoryID = new Guid("1a421152-cf67-4eda-af8e-61e490f9dddd"),
                            TagID = new Guid("5f9499ee-8cdb-457a-b09d-95c5b84cb379")
                        });
                });

            modelBuilder.Entity("WebApi.Models.Entities.ColorEntity", b =>
                {
                    b.Property<Guid>("ColorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColorID");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorID = new Guid("9c397b76-f1b3-41fa-8864-ae1ea121e213"),
                            ColorName = "red"
                        },
                        new
                        {
                            ColorID = new Guid("743a791b-0cee-4493-a888-e9e29efbedf7"),
                            ColorName = "green"
                        },
                        new
                        {
                            ColorID = new Guid("c176069f-e0e5-456d-854a-a2d9d6fe0854"),
                            ColorName = "blue"
                        },
                        new
                        {
                            ColorID = new Guid("9d581bab-6476-4f85-8ad0-79931c753a67"),
                            ColorName = "black"
                        },
                        new
                        {
                            ColorID = new Guid("409911df-3613-49e3-adcb-2305a7bb1683"),
                            ColorName = "white"
                        },
                        new
                        {
                            ColorID = new Guid("03c6863e-8c30-4087-a211-b72335617a3e"),
                            ColorName = "brown"
                        },
                        new
                        {
                            ColorID = new Guid("bd8dfeb7-5b29-4bc0-a1f8-1fbf4c77ef8f"),
                            ColorName = "yellow"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Entities.ImageEntity", b =>
                {
                    b.Property<Guid>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageID");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageID = new Guid("ea3065d9-43de-424c-8f19-d8b8c64a421e"),
                            ImageName = "party parrot",
                            ImagePath = "https://ih1.redbubble.net/image.293970198.3497/st,small,507x507-pad,600x600,f8f8f8.u2.jpg"
                        },
                        new
                        {
                            ImageID = new Guid("8cf79865-6503-425c-a82e-282269b19189"),
                            ImageName = "JulMust",
                            ImagePath = "https://cdn2.cdnme.se/1970309/7-3/10613102_965889760093054_3668906844852005056_n_542e67509606ee4a4e88b4c2.jpg"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Entities.ProductCategoryEntity", b =>
                {
                    b.Property<Guid>("ProductCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductCategoryID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductCategoryID = new Guid("8149778f-60a0-48e2-a5e0-68eec3c92603"),
                            CategoryID = new Guid("7bce8f5a-6e92-4472-9168-eb4a8506c6bf"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5")
                        },
                        new
                        {
                            ProductCategoryID = new Guid("fece9268-ae1e-4a27-8077-f6e6fbb76a6f"),
                            CategoryID = new Guid("7bce8f5a-6e92-4472-9168-eb4a8506c6bf"),
                            ProductID = new Guid("209f2710-32b9-4fe7-9d04-470c931184a1")
                        },
                        new
                        {
                            ProductCategoryID = new Guid("aa815498-aa03-4780-80de-dbf80513f514"),
                            CategoryID = new Guid("7bce8f5a-6e92-4472-9168-eb4a8506c6bf"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f")
                        },
                        new
                        {
                            ProductCategoryID = new Guid("77e798a5-423d-4a60-b140-08667b0f743f"),
                            CategoryID = new Guid("7bce8f5a-6e92-4472-9168-eb4a8506c6bf"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c")
                        },
                        new
                        {
                            ProductCategoryID = new Guid("9f841375-1869-4cea-b218-b03b8166bf37"),
                            CategoryID = new Guid("e540be20-c17d-4e5a-aebd-0733c7955cdb"),
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379")
                        },
                        new
                        {
                            ProductCategoryID = new Guid("53a12c36-bf20-4711-a15f-b4846f8cc628"),
                            CategoryID = new Guid("e540be20-c17d-4e5a-aebd-0733c7955cdb"),
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac")
                        },
                        new
                        {
                            ProductCategoryID = new Guid("df4ee232-65d5-43ce-b411-23433c13a905"),
                            CategoryID = new Guid("e540be20-c17d-4e5a-aebd-0733c7955cdb"),
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254")
                        },
                        new
                        {
                            ProductCategoryID = new Guid("0cb57263-3bf3-4a53-b440-0296defdc229"),
                            CategoryID = new Guid("e540be20-c17d-4e5a-aebd-0733c7955cdb"),
                            ProductID = new Guid("8c335be4-5cd9-4df0-8bc7-b6322ea41ec2")
                        },
                        new
                        {
                            ProductCategoryID = new Guid("fef4966d-492a-4c68-92c3-ce1900b2dd84"),
                            CategoryID = new Guid("e540be20-c17d-4e5a-aebd-0733c7955cdb"),
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254")
                        },
                        new
                        {
                            ProductCategoryID = new Guid("fe971b6e-5296-48d1-b72d-a1784efdfeda"),
                            CategoryID = new Guid("e540be20-c17d-4e5a-aebd-0733c7955cdb"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c")
                        },
                        new
                        {
                            ProductCategoryID = new Guid("950b70da-9751-49e7-b028-bc7849f9b6c8"),
                            CategoryID = new Guid("b39664eb-6934-4dcd-986e-7c6cf0efb8c9"),
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad")
                        },
                        new
                        {
                            ProductCategoryID = new Guid("79917b5c-f382-47e9-b72f-57ec252dbf36"),
                            CategoryID = new Guid("b39664eb-6934-4dcd-986e-7c6cf0efb8c9"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8")
                        },
                        new
                        {
                            ProductCategoryID = new Guid("38f3c6d5-5d60-448d-b482-5bb9f3c851c8"),
                            CategoryID = new Guid("1a421152-cf67-4eda-af8e-61e490f9dddd"),
                            ProductID = new Guid("4592ed37-1361-4761-a3dd-3654670006ce")
                        },
                        new
                        {
                            ProductCategoryID = new Guid("a3306134-8458-4f5a-aa52-69c564793267"),
                            CategoryID = new Guid("1a421152-cf67-4eda-af8e-61e490f9dddd"),
                            ProductID = new Guid("6724d1cf-0d30-4723-8f61-ddf0174df9f7")
                        });
                });

            modelBuilder.Entity("WebApi.Models.Entities.ProductColorEntity", b =>
                {
                    b.Property<Guid>("ProductColorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductColorID");

                    b.HasIndex("ColorID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductColors");

                    b.HasData(
                        new
                        {
                            ProductColorID = new Guid("4fa4d59c-de80-4cc3-946f-ad3f57fa467a"),
                            ColorID = new Guid("9c397b76-f1b3-41fa-8864-ae1ea121e213"),
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379")
                        },
                        new
                        {
                            ProductColorID = new Guid("ddbefb7e-e18c-466b-9998-9525eb618504"),
                            ColorID = new Guid("9c397b76-f1b3-41fa-8864-ae1ea121e213"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f")
                        },
                        new
                        {
                            ProductColorID = new Guid("a830ac63-6868-4f2f-b02c-dce1d1cc5160"),
                            ColorID = new Guid("9c397b76-f1b3-41fa-8864-ae1ea121e213"),
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac")
                        },
                        new
                        {
                            ProductColorID = new Guid("ba262e11-c590-42b1-8d9b-d9f48d60ddd9"),
                            ColorID = new Guid("9c397b76-f1b3-41fa-8864-ae1ea121e213"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5")
                        },
                        new
                        {
                            ProductColorID = new Guid("eec22ba8-52d0-4064-aeb8-de88797aaacc"),
                            ColorID = new Guid("9c397b76-f1b3-41fa-8864-ae1ea121e213"),
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254")
                        },
                        new
                        {
                            ProductColorID = new Guid("b7a1136b-b8c1-4703-9a63-d69267e211c9"),
                            ColorID = new Guid("743a791b-0cee-4493-a888-e9e29efbedf7"),
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379")
                        },
                        new
                        {
                            ProductColorID = new Guid("02cae471-c7e6-4e0c-84cc-a800ea738df7"),
                            ColorID = new Guid("c176069f-e0e5-456d-854a-a2d9d6fe0854"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f")
                        },
                        new
                        {
                            ProductColorID = new Guid("9a4d38f7-ee0f-4492-8886-e943d79cc583"),
                            ColorID = new Guid("743a791b-0cee-4493-a888-e9e29efbedf7"),
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac")
                        },
                        new
                        {
                            ProductColorID = new Guid("bb125a33-1ec4-441c-b636-4bf9901aafcb"),
                            ColorID = new Guid("bd8dfeb7-5b29-4bc0-a1f8-1fbf4c77ef8f"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5")
                        },
                        new
                        {
                            ProductColorID = new Guid("c77d0f80-8d22-43cc-8eaf-552c2788e6f1"),
                            ColorID = new Guid("c176069f-e0e5-456d-854a-a2d9d6fe0854"),
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254")
                        },
                        new
                        {
                            ProductColorID = new Guid("a910933b-d893-4268-9fea-a018afbb5479"),
                            ColorID = new Guid("743a791b-0cee-4493-a888-e9e29efbedf7"),
                            ProductID = new Guid("209f2710-32b9-4fe7-9d04-470c931184a1")
                        },
                        new
                        {
                            ProductColorID = new Guid("aa5b3f98-0553-4124-8871-73e51df91633"),
                            ColorID = new Guid("743a791b-0cee-4493-a888-e9e29efbedf7"),
                            ProductID = new Guid("8c335be4-5cd9-4df0-8bc7-b6322ea41ec2")
                        },
                        new
                        {
                            ProductColorID = new Guid("62c4a1ec-5025-42e8-8894-42b82adf6263"),
                            ColorID = new Guid("bd8dfeb7-5b29-4bc0-a1f8-1fbf4c77ef8f"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8")
                        },
                        new
                        {
                            ProductColorID = new Guid("c390b69b-1641-4ffe-a4a0-94cb114b80a9"),
                            ColorID = new Guid("743a791b-0cee-4493-a888-e9e29efbedf7"),
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad")
                        },
                        new
                        {
                            ProductColorID = new Guid("e0ed4e01-1cb1-4674-bfd2-c55011c0792a"),
                            ColorID = new Guid("c176069f-e0e5-456d-854a-a2d9d6fe0854"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c")
                        },
                        new
                        {
                            ProductColorID = new Guid("0d0233f4-8982-4516-9dcd-454264a4ab6e"),
                            ColorID = new Guid("743a791b-0cee-4493-a888-e9e29efbedf7"),
                            ProductID = new Guid("4592ed37-1361-4761-a3dd-3654670006ce")
                        },
                        new
                        {
                            ProductColorID = new Guid("a64e26ac-79ef-4788-a5a0-7bd43d3448b7"),
                            ColorID = new Guid("c176069f-e0e5-456d-854a-a2d9d6fe0854"),
                            ProductID = new Guid("6724d1cf-0d30-4723-8f61-ddf0174df9f7")
                        },
                        new
                        {
                            ProductColorID = new Guid("1239917c-92df-4a01-8e4c-964eb1c6423d"),
                            ColorID = new Guid("c176069f-e0e5-456d-854a-a2d9d6fe0854"),
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379")
                        },
                        new
                        {
                            ProductColorID = new Guid("2621cf2d-1607-4c24-94a5-4db0cb77dbeb"),
                            ColorID = new Guid("03c6863e-8c30-4087-a211-b72335617a3e"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f")
                        },
                        new
                        {
                            ProductColorID = new Guid("70831cff-c30a-4c64-86f5-63900f9e15e4"),
                            ColorID = new Guid("bd8dfeb7-5b29-4bc0-a1f8-1fbf4c77ef8f"),
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac")
                        },
                        new
                        {
                            ProductColorID = new Guid("f86c2868-70ca-467f-a071-1dd58eb6cb27"),
                            ColorID = new Guid("03c6863e-8c30-4087-a211-b72335617a3e"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5")
                        },
                        new
                        {
                            ProductColorID = new Guid("83aa44bc-d821-462b-af48-0926356f214e"),
                            ColorID = new Guid("c176069f-e0e5-456d-854a-a2d9d6fe0854"),
                            ProductID = new Guid("209f2710-32b9-4fe7-9d04-470c931184a1")
                        },
                        new
                        {
                            ProductColorID = new Guid("a378ba0f-bda6-4006-b7cf-fdc1af2938db"),
                            ColorID = new Guid("03c6863e-8c30-4087-a211-b72335617a3e"),
                            ProductID = new Guid("8c335be4-5cd9-4df0-8bc7-b6322ea41ec2")
                        },
                        new
                        {
                            ProductColorID = new Guid("64d17fce-cf0d-48ea-888f-9214e5b5def1"),
                            ColorID = new Guid("c176069f-e0e5-456d-854a-a2d9d6fe0854"),
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad")
                        },
                        new
                        {
                            ProductColorID = new Guid("ac21c705-b50a-4d9e-8af2-a6e666b7bbc4"),
                            ColorID = new Guid("bd8dfeb7-5b29-4bc0-a1f8-1fbf4c77ef8f"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c")
                        },
                        new
                        {
                            ProductColorID = new Guid("226dddb4-2c73-4a7b-9dfd-aef7f9a10bf5"),
                            ColorID = new Guid("c176069f-e0e5-456d-854a-a2d9d6fe0854"),
                            ProductID = new Guid("4592ed37-1361-4761-a3dd-3654670006ce")
                        },
                        new
                        {
                            ProductColorID = new Guid("88c3d05e-6137-487b-9388-b61d4be5fa19"),
                            ColorID = new Guid("03c6863e-8c30-4087-a211-b72335617a3e"),
                            ProductID = new Guid("6724d1cf-0d30-4723-8f61-ddf0174df9f7")
                        },
                        new
                        {
                            ProductColorID = new Guid("af757366-0787-4246-bb5a-61577fe0fcf3"),
                            ColorID = new Guid("9d581bab-6476-4f85-8ad0-79931c753a67"),
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379")
                        },
                        new
                        {
                            ProductColorID = new Guid("c419946a-82ab-4a52-90f3-0cddfe661d40"),
                            ColorID = new Guid("9d581bab-6476-4f85-8ad0-79931c753a67"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f")
                        },
                        new
                        {
                            ProductColorID = new Guid("36b52db2-13cd-49b6-b037-b6f74732af2b"),
                            ColorID = new Guid("9d581bab-6476-4f85-8ad0-79931c753a67"),
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac")
                        },
                        new
                        {
                            ProductColorID = new Guid("ce0b2d26-c9a2-495a-ae1a-4532e5ee6d90"),
                            ColorID = new Guid("9d581bab-6476-4f85-8ad0-79931c753a67"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5")
                        },
                        new
                        {
                            ProductColorID = new Guid("cdf4be39-cf5e-407e-a015-f109757e642d"),
                            ColorID = new Guid("9d581bab-6476-4f85-8ad0-79931c753a67"),
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254")
                        },
                        new
                        {
                            ProductColorID = new Guid("7de24902-56d3-4e2a-8c56-61cb423ce95b"),
                            ColorID = new Guid("9d581bab-6476-4f85-8ad0-79931c753a67"),
                            ProductID = new Guid("209f2710-32b9-4fe7-9d04-470c931184a1")
                        },
                        new
                        {
                            ProductColorID = new Guid("0dfb87b7-deef-45cb-ae02-b8d5c5c9a2b5"),
                            ColorID = new Guid("9d581bab-6476-4f85-8ad0-79931c753a67"),
                            ProductID = new Guid("8c335be4-5cd9-4df0-8bc7-b6322ea41ec2")
                        },
                        new
                        {
                            ProductColorID = new Guid("9a1541f2-6281-4039-a71f-16f1c68e7468"),
                            ColorID = new Guid("9d581bab-6476-4f85-8ad0-79931c753a67"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8")
                        },
                        new
                        {
                            ProductColorID = new Guid("ed46a00b-33c5-4ff9-8dab-93a61094d5f3"),
                            ColorID = new Guid("9d581bab-6476-4f85-8ad0-79931c753a67"),
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad")
                        },
                        new
                        {
                            ProductColorID = new Guid("738a017e-2ff1-4e24-8669-4d05618ecb42"),
                            ColorID = new Guid("9d581bab-6476-4f85-8ad0-79931c753a67"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c")
                        },
                        new
                        {
                            ProductColorID = new Guid("85cf8af4-bd29-4bdb-ae77-81b858d36aed"),
                            ColorID = new Guid("9d581bab-6476-4f85-8ad0-79931c753a67"),
                            ProductID = new Guid("4592ed37-1361-4761-a3dd-3654670006ce")
                        },
                        new
                        {
                            ProductColorID = new Guid("dda0a140-44d3-4b57-97d4-1508bb2e6c4d"),
                            ColorID = new Guid("9d581bab-6476-4f85-8ad0-79931c753a67"),
                            ProductID = new Guid("6724d1cf-0d30-4723-8f61-ddf0174df9f7")
                        },
                        new
                        {
                            ProductColorID = new Guid("74c6adf7-8173-40ea-b098-bcf0198dd7e5"),
                            ColorID = new Guid("409911df-3613-49e3-adcb-2305a7bb1683"),
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379")
                        },
                        new
                        {
                            ProductColorID = new Guid("18497914-1dc7-43fb-b1f1-206e83196fec"),
                            ColorID = new Guid("409911df-3613-49e3-adcb-2305a7bb1683"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f")
                        },
                        new
                        {
                            ProductColorID = new Guid("7ace1163-feb9-4dce-96ee-ffbae51c2ce8"),
                            ColorID = new Guid("409911df-3613-49e3-adcb-2305a7bb1683"),
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac")
                        },
                        new
                        {
                            ProductColorID = new Guid("97816d45-7999-4e31-a00b-c46a1d180865"),
                            ColorID = new Guid("409911df-3613-49e3-adcb-2305a7bb1683"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5")
                        },
                        new
                        {
                            ProductColorID = new Guid("72933f4c-0580-4dd0-b543-fa11f43d2dc4"),
                            ColorID = new Guid("409911df-3613-49e3-adcb-2305a7bb1683"),
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254")
                        },
                        new
                        {
                            ProductColorID = new Guid("b93a1810-6e96-4421-a7a0-5351e216cd37"),
                            ColorID = new Guid("409911df-3613-49e3-adcb-2305a7bb1683"),
                            ProductID = new Guid("209f2710-32b9-4fe7-9d04-470c931184a1")
                        },
                        new
                        {
                            ProductColorID = new Guid("d779f457-4ba1-41d5-9947-a46f0e713427"),
                            ColorID = new Guid("409911df-3613-49e3-adcb-2305a7bb1683"),
                            ProductID = new Guid("8c335be4-5cd9-4df0-8bc7-b6322ea41ec2")
                        },
                        new
                        {
                            ProductColorID = new Guid("32d06e38-c0f7-4412-90e5-f64775c522ea"),
                            ColorID = new Guid("409911df-3613-49e3-adcb-2305a7bb1683"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8")
                        },
                        new
                        {
                            ProductColorID = new Guid("854ac395-a60a-4ce8-8f01-6c5c6afc84ae"),
                            ColorID = new Guid("409911df-3613-49e3-adcb-2305a7bb1683"),
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad")
                        },
                        new
                        {
                            ProductColorID = new Guid("95795e38-a377-4806-bd3a-6a5c029f730b"),
                            ColorID = new Guid("409911df-3613-49e3-adcb-2305a7bb1683"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c")
                        },
                        new
                        {
                            ProductColorID = new Guid("270de448-e1a4-4ed8-b9aa-01adaa79ed29"),
                            ColorID = new Guid("409911df-3613-49e3-adcb-2305a7bb1683"),
                            ProductID = new Guid("4592ed37-1361-4761-a3dd-3654670006ce")
                        },
                        new
                        {
                            ProductColorID = new Guid("de9c8526-5596-4fe8-8f8a-60cbd46b2ae4"),
                            ColorID = new Guid("409911df-3613-49e3-adcb-2305a7bb1683"),
                            ProductID = new Guid("6724d1cf-0d30-4723-8f61-ddf0174df9f7")
                        });
                });

            modelBuilder.Entity("WebApi.Models.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379"),
                            CreatedDate = new DateTime(2023, 11, 14, 10, 12, 40, 245, DateTimeKind.Local).AddTicks(5674),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed etiam, in codice quem attulisti, apparet confusio in syntaxi. Videtur quod coneris instaurare novam instantiationem classis CategoryEntity. Verum modus quo scriptum est flibbertigibbet, potest esse causa difficultatis. Flibbertigibbet requirit parametrum stringae, quod debet repraesentare formatum mumbo jumbo idoneum.",
                            Price = 12.12m,
                            ProductName = "EleganceVogue Dress",
                            Rating = 3.5
                        },
                        new
                        {
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f"),
                            CreatedDate = new DateTime(2023, 11, 14, 10, 12, 40, 245, DateTimeKind.Local).AddTicks(5720),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed etiam, in codice quem attulisti, apparet confusio in syntaxi. Videtur quod coneris instaurare novam instantiationem classis CategoryEntity. Verum modus quo scriptum est flibbertigibbet, potest esse causa difficultatis. Flibbertigibbet requirit parametrum stringae, quod debet repraesentare formatum mumbo jumbo idoneum.",
                            Price = 13.45m,
                            ProductName = "UrbanChic Denim Jeans",
                            Rating = 3.7999999999999998
                        },
                        new
                        {
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac"),
                            CreatedDate = new DateTime(2023, 11, 14, 11, 12, 40, 245, DateTimeKind.Local).AddTicks(5723),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed etiam, in codice quem attulisti, apparet confusio in syntaxi. Videtur quod coneris instaurare novam instantiationem classis CategoryEntity. Verum modus quo scriptum est flibbertigibbet, potest esse causa difficultatis. Flibbertigibbet requirit parametrum stringae, quod debet repraesentare formatum mumbo jumbo idoneum.",
                            Price = 12.99m,
                            ProductName = "CosmoFlair Blouse",
                            Rating = 4.2000000000000002,
                            SalePrice = 10.20m
                        },
                        new
                        {
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5"),
                            CreatedDate = new DateTime(2023, 11, 14, 9, 12, 40, 245, DateTimeKind.Local).AddTicks(5726),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed etiam, in codice quem attulisti, apparet confusio in syntaxi. Videtur quod coneris instaurare novam instantiationem classis CategoryEntity. Verum modus quo scriptum est flibbertigibbet, potest esse causa difficultatis. Flibbertigibbet requirit parametrum stringae, quod debet repraesentare formatum mumbo jumbo idoneum.",
                            Price = 10.58m,
                            ProductName = "StrideFlex Sneakers",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254"),
                            CreatedDate = new DateTime(2023, 11, 14, 9, 12, 40, 245, DateTimeKind.Local).AddTicks(5729),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed etiam, in codice quem attulisti, apparet confusio in syntaxi. Videtur quod coneris instaurare novam instantiationem classis CategoryEntity. Verum modus quo scriptum est flibbertigibbet, potest esse causa difficultatis. Flibbertigibbet requirit parametrum stringae, quod debet repraesentare formatum mumbo jumbo idoneum.",
                            Price = 16.12m,
                            ProductName = "AzureGlow Summer Dress",
                            Rating = 5.0,
                            SalePrice = 11.98m
                        },
                        new
                        {
                            ProductID = new Guid("209f2710-32b9-4fe7-9d04-470c931184a1"),
                            CreatedDate = new DateTime(2023, 11, 14, 8, 12, 40, 245, DateTimeKind.Local).AddTicks(5732),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed etiam, in codice quem attulisti, apparet confusio in syntaxi. Videtur quod coneris instaurare novam instantiationem classis CategoryEntity. Verum modus quo scriptum est flibbertigibbet, potest esse causa difficultatis. Flibbertigibbet requirit parametrum stringae, quod debet repraesentare formatum mumbo jumbo idoneum.",
                            Price = 16.89m,
                            ProductName = "GentleBreeze Linen Shirt",
                            Rating = 1.3,
                            SalePrice = 13.78m
                        },
                        new
                        {
                            ProductID = new Guid("8c335be4-5cd9-4df0-8bc7-b6322ea41ec2"),
                            CreatedDate = new DateTime(2023, 11, 14, 8, 12, 40, 245, DateTimeKind.Local).AddTicks(5734),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed etiam, in codice quem attulisti, apparet confusio in syntaxi. Videtur quod coneris instaurare novam instantiationem classis CategoryEntity. Verum modus quo scriptum est flibbertigibbet, potest esse causa difficultatis. Flibbertigibbet requirit parametrum stringae, quod debet repraesentare formatum mumbo jumbo idoneum.",
                            Price = 19.50m,
                            ProductName = "TwilightGlam Evening Gown",
                            Rating = 1.7
                        },
                        new
                        {
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8"),
                            CreatedDate = new DateTime(2023, 11, 14, 7, 12, 40, 245, DateTimeKind.Local).AddTicks(5737),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed etiam, in codice quem attulisti, apparet confusio in syntaxi. Videtur quod coneris instaurare novam instantiationem classis CategoryEntity. Verum modus quo scriptum est flibbertigibbet, potest esse causa difficultatis. Flibbertigibbet requirit parametrum stringae, quod debet repraesentare formatum mumbo jumbo idoneum.",
                            Price = 14.89m,
                            ProductName = "TrendSetGo Jumpsuit",
                            Rating = 2.6000000000000001,
                            SalePrice = 12.34m
                        },
                        new
                        {
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad"),
                            CreatedDate = new DateTime(2023, 11, 14, 7, 12, 40, 245, DateTimeKind.Local).AddTicks(5740),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed etiam, in codice quem attulisti, apparet confusio in syntaxi. Videtur quod coneris instaurare novam instantiationem classis CategoryEntity. Verum modus quo scriptum est flibbertigibbet, potest esse causa difficultatis. Flibbertigibbet requirit parametrum stringae, quod debet repraesentare formatum mumbo jumbo idoneum.",
                            Price = 17.78m,
                            ProductName = "CottonCloud Lounge Pants",
                            Rating = 2.8999999999999999
                        },
                        new
                        {
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c"),
                            CreatedDate = new DateTime(2023, 11, 14, 6, 12, 40, 245, DateTimeKind.Local).AddTicks(5742),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed etiam, in codice quem attulisti, apparet confusio in syntaxi. Videtur quod coneris instaurare novam instantiationem classis CategoryEntity. Verum modus quo scriptum est flibbertigibbet, potest esse causa difficultatis. Flibbertigibbet requirit parametrum stringae, quod debet repraesentare formatum mumbo jumbo idoneum.",
                            Price = 12.50m,
                            ProductName = "PeakPerformance Activewear",
                            Rating = 3.0
                        },
                        new
                        {
                            ProductID = new Guid("4592ed37-1361-4761-a3dd-3654670006ce"),
                            CreatedDate = new DateTime(2023, 11, 14, 7, 12, 40, 245, DateTimeKind.Local).AddTicks(5745),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed etiam, in codice quem attulisti, apparet confusio in syntaxi. Videtur quod coneris instaurare novam instantiationem classis CategoryEntity. Verum modus quo scriptum est flibbertigibbet, potest esse causa difficultatis. Flibbertigibbet requirit parametrum stringae, quod debet repraesentare formatum mumbo jumbo idoneum.",
                            Price = 17.78m,
                            ProductName = "UrbanBlend Aviator Sunglasses",
                            Rating = 2.8999999999999999
                        },
                        new
                        {
                            ProductID = new Guid("6724d1cf-0d30-4723-8f61-ddf0174df9f7"),
                            CreatedDate = new DateTime(2023, 11, 14, 6, 12, 40, 245, DateTimeKind.Local).AddTicks(5747),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed etiam, in codice quem attulisti, apparet confusio in syntaxi. Videtur quod coneris instaurare novam instantiationem classis CategoryEntity. Verum modus quo scriptum est flibbertigibbet, potest esse causa difficultatis. Flibbertigibbet requirit parametrum stringae, quod debet repraesentare formatum mumbo jumbo idoneum.",
                            Price = 12.50m,
                            ProductName = "StrideFlex Leather Belt",
                            Rating = 3.0
                        });
                });

            modelBuilder.Entity("WebApi.Models.Entities.ProductImageEntity", b =>
                {
                    b.Property<Guid>("ProductImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ImageID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductImageID");

                    b.HasIndex("ImageID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            ProductImageID = new Guid("a87271bc-683e-419d-a2aa-70a64300fcaf"),
                            ImageID = new Guid("ea3065d9-43de-424c-8f19-d8b8c64a421e"),
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379")
                        },
                        new
                        {
                            ProductImageID = new Guid("af3ec737-c6f1-4b70-8e24-5d2a1f45cde6"),
                            ImageID = new Guid("ea3065d9-43de-424c-8f19-d8b8c64a421e"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f")
                        },
                        new
                        {
                            ProductImageID = new Guid("5e2f6481-e885-4e09-907d-4daccb26898b"),
                            ImageID = new Guid("ea3065d9-43de-424c-8f19-d8b8c64a421e"),
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac")
                        },
                        new
                        {
                            ProductImageID = new Guid("99ca4e18-9725-41d0-8d06-cc911bc0b3d2"),
                            ImageID = new Guid("ea3065d9-43de-424c-8f19-d8b8c64a421e"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5")
                        },
                        new
                        {
                            ProductImageID = new Guid("56cb820e-2905-418f-8108-9094a5e7ae61"),
                            ImageID = new Guid("ea3065d9-43de-424c-8f19-d8b8c64a421e"),
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254")
                        },
                        new
                        {
                            ProductImageID = new Guid("8d777702-3562-4298-8889-639b0cd79d10"),
                            ImageID = new Guid("ea3065d9-43de-424c-8f19-d8b8c64a421e"),
                            ProductID = new Guid("209f2710-32b9-4fe7-9d04-470c931184a1")
                        },
                        new
                        {
                            ProductImageID = new Guid("bec0d0d6-1ece-4852-8107-bb30597d9ab0"),
                            ImageID = new Guid("ea3065d9-43de-424c-8f19-d8b8c64a421e"),
                            ProductID = new Guid("8c335be4-5cd9-4df0-8bc7-b6322ea41ec2")
                        },
                        new
                        {
                            ProductImageID = new Guid("2ae1fa5b-bd84-4604-adfe-ffcd8f687372"),
                            ImageID = new Guid("ea3065d9-43de-424c-8f19-d8b8c64a421e"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8")
                        },
                        new
                        {
                            ProductImageID = new Guid("a32f357e-a7bc-4995-9aaa-ef6bfcecac0f"),
                            ImageID = new Guid("ea3065d9-43de-424c-8f19-d8b8c64a421e"),
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad")
                        },
                        new
                        {
                            ProductImageID = new Guid("0d1fd992-8d0a-45a8-bf52-4363f89e656d"),
                            ImageID = new Guid("ea3065d9-43de-424c-8f19-d8b8c64a421e"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c")
                        },
                        new
                        {
                            ProductImageID = new Guid("f3b4153b-2013-4ae7-b139-583f66fa7d2e"),
                            ImageID = new Guid("ea3065d9-43de-424c-8f19-d8b8c64a421e"),
                            ProductID = new Guid("4592ed37-1361-4761-a3dd-3654670006ce")
                        },
                        new
                        {
                            ProductImageID = new Guid("3ea6f8ac-58d6-4b90-9c34-997445a8a499"),
                            ImageID = new Guid("ea3065d9-43de-424c-8f19-d8b8c64a421e"),
                            ProductID = new Guid("6724d1cf-0d30-4723-8f61-ddf0174df9f7")
                        },
                        new
                        {
                            ProductImageID = new Guid("9e0e425c-e869-43b8-9009-451b6d78983c"),
                            ImageID = new Guid("8cf79865-6503-425c-a82e-282269b19189"),
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379")
                        },
                        new
                        {
                            ProductImageID = new Guid("d6624080-df68-4bad-a1d3-c293d3433bed"),
                            ImageID = new Guid("8cf79865-6503-425c-a82e-282269b19189"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f")
                        },
                        new
                        {
                            ProductImageID = new Guid("3dc3e380-2383-43c3-87cf-f6646c97ea44"),
                            ImageID = new Guid("8cf79865-6503-425c-a82e-282269b19189"),
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac")
                        },
                        new
                        {
                            ProductImageID = new Guid("2c0560a7-9856-4373-8d7e-9e71227a99eb"),
                            ImageID = new Guid("8cf79865-6503-425c-a82e-282269b19189"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5")
                        },
                        new
                        {
                            ProductImageID = new Guid("06f35b9e-4e7e-4cbf-8798-0dd71ce37ce4"),
                            ImageID = new Guid("8cf79865-6503-425c-a82e-282269b19189"),
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254")
                        },
                        new
                        {
                            ProductImageID = new Guid("88a45aa0-0d9b-46ec-a634-01ab5731377c"),
                            ImageID = new Guid("8cf79865-6503-425c-a82e-282269b19189"),
                            ProductID = new Guid("209f2710-32b9-4fe7-9d04-470c931184a1")
                        },
                        new
                        {
                            ProductImageID = new Guid("09462a98-58b2-4a67-9553-12475c677ad4"),
                            ImageID = new Guid("8cf79865-6503-425c-a82e-282269b19189"),
                            ProductID = new Guid("8c335be4-5cd9-4df0-8bc7-b6322ea41ec2")
                        },
                        new
                        {
                            ProductImageID = new Guid("0f732451-26b6-451e-aaf8-6c3fefa5fdff"),
                            ImageID = new Guid("8cf79865-6503-425c-a82e-282269b19189"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8")
                        },
                        new
                        {
                            ProductImageID = new Guid("d63f24a2-12ce-4a86-bf61-1bad85cb9d6b"),
                            ImageID = new Guid("8cf79865-6503-425c-a82e-282269b19189"),
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad")
                        },
                        new
                        {
                            ProductImageID = new Guid("957bdd6c-6100-41bc-9dae-26b02f45de15"),
                            ImageID = new Guid("8cf79865-6503-425c-a82e-282269b19189"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c")
                        },
                        new
                        {
                            ProductImageID = new Guid("db9dbc50-89f4-4d23-996e-10cc775676c9"),
                            ImageID = new Guid("8cf79865-6503-425c-a82e-282269b19189"),
                            ProductID = new Guid("4592ed37-1361-4761-a3dd-3654670006ce")
                        },
                        new
                        {
                            ProductImageID = new Guid("28812f85-28d5-40f1-b3b7-e76a47f126aa"),
                            ImageID = new Guid("8cf79865-6503-425c-a82e-282269b19189"),
                            ProductID = new Guid("6724d1cf-0d30-4723-8f61-ddf0174df9f7")
                        });
                });

            modelBuilder.Entity("WebApi.Models.Entities.ProductReviewEntity", b =>
                {
                    b.Property<Guid>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("WebApi.Models.Entities.ProductSizeEntity", b =>
                {
                    b.Property<Guid>("ProductSizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SizeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductSizeID");

                    b.HasIndex("ProductID");

                    b.HasIndex("SizeID");

                    b.ToTable("ProductSizes");

                    b.HasData(
                        new
                        {
                            ProductSizeID = new Guid("5b9d34d3-987c-44ab-862d-98958c83feec"),
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379"),
                            SizeID = new Guid("462e8f20-0c38-4c39-b39e-b2d5d651b24e")
                        },
                        new
                        {
                            ProductSizeID = new Guid("114e506d-5915-43b7-bbac-6378a9fb9a7e"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f"),
                            SizeID = new Guid("462e8f20-0c38-4c39-b39e-b2d5d651b24e")
                        },
                        new
                        {
                            ProductSizeID = new Guid("8472fb6c-b740-4e69-8da5-55031c467a67"),
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac"),
                            SizeID = new Guid("462e8f20-0c38-4c39-b39e-b2d5d651b24e")
                        },
                        new
                        {
                            ProductSizeID = new Guid("885ba838-f955-4b7d-bbce-0d89f5b4f599"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5"),
                            SizeID = new Guid("462e8f20-0c38-4c39-b39e-b2d5d651b24e")
                        },
                        new
                        {
                            ProductSizeID = new Guid("2232c876-983a-4bbe-9892-bd523ca2e6ae"),
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254"),
                            SizeID = new Guid("462e8f20-0c38-4c39-b39e-b2d5d651b24e")
                        },
                        new
                        {
                            ProductSizeID = new Guid("73bffb85-42cf-49de-b230-784d59bd4d0a"),
                            ProductID = new Guid("209f2710-32b9-4fe7-9d04-470c931184a1"),
                            SizeID = new Guid("462e8f20-0c38-4c39-b39e-b2d5d651b24e")
                        },
                        new
                        {
                            ProductSizeID = new Guid("38cb91f5-2566-4670-8da7-e04462380406"),
                            ProductID = new Guid("8c335be4-5cd9-4df0-8bc7-b6322ea41ec2"),
                            SizeID = new Guid("462e8f20-0c38-4c39-b39e-b2d5d651b24e")
                        },
                        new
                        {
                            ProductSizeID = new Guid("7ea63599-ab2a-4774-ad6a-455e560a4e05"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8"),
                            SizeID = new Guid("462e8f20-0c38-4c39-b39e-b2d5d651b24e")
                        },
                        new
                        {
                            ProductSizeID = new Guid("3cef233a-2d53-4876-891a-9e705fc34162"),
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad"),
                            SizeID = new Guid("462e8f20-0c38-4c39-b39e-b2d5d651b24e")
                        },
                        new
                        {
                            ProductSizeID = new Guid("bad81476-940b-4bc5-a917-aa0038b2804d"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c"),
                            SizeID = new Guid("462e8f20-0c38-4c39-b39e-b2d5d651b24e")
                        },
                        new
                        {
                            ProductSizeID = new Guid("b58fea46-9488-439c-a489-a61a6b0f5b22"),
                            ProductID = new Guid("4592ed37-1361-4761-a3dd-3654670006ce"),
                            SizeID = new Guid("462e8f20-0c38-4c39-b39e-b2d5d651b24e")
                        },
                        new
                        {
                            ProductSizeID = new Guid("174ad57e-e9be-404f-948b-f1990bec5648"),
                            ProductID = new Guid("6724d1cf-0d30-4723-8f61-ddf0174df9f7"),
                            SizeID = new Guid("462e8f20-0c38-4c39-b39e-b2d5d651b24e")
                        },
                        new
                        {
                            ProductSizeID = new Guid("bd15ce43-5f86-4903-b800-c83b5bb76d98"),
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379"),
                            SizeID = new Guid("9d7ff143-3e26-40ae-ab00-2fead9950a03")
                        },
                        new
                        {
                            ProductSizeID = new Guid("9b44f228-3aa7-4131-a8e4-b9f653e13f66"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f"),
                            SizeID = new Guid("9d7ff143-3e26-40ae-ab00-2fead9950a03")
                        },
                        new
                        {
                            ProductSizeID = new Guid("15ddbc37-03f6-4a2d-8213-d71233b6aa78"),
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac"),
                            SizeID = new Guid("9d7ff143-3e26-40ae-ab00-2fead9950a03")
                        },
                        new
                        {
                            ProductSizeID = new Guid("7f5be492-44e5-4955-a2fe-275653a4ef72"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5"),
                            SizeID = new Guid("9d7ff143-3e26-40ae-ab00-2fead9950a03")
                        },
                        new
                        {
                            ProductSizeID = new Guid("00077cb0-fa96-4dea-a07b-4c4fee97993a"),
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254"),
                            SizeID = new Guid("9d7ff143-3e26-40ae-ab00-2fead9950a03")
                        },
                        new
                        {
                            ProductSizeID = new Guid("b0328602-6fef-4032-a7bb-f9fae8c945b0"),
                            ProductID = new Guid("209f2710-32b9-4fe7-9d04-470c931184a1"),
                            SizeID = new Guid("9d7ff143-3e26-40ae-ab00-2fead9950a03")
                        },
                        new
                        {
                            ProductSizeID = new Guid("e4c80281-7d33-4a8e-a458-67d4e1a78947"),
                            ProductID = new Guid("8c335be4-5cd9-4df0-8bc7-b6322ea41ec2"),
                            SizeID = new Guid("9d7ff143-3e26-40ae-ab00-2fead9950a03")
                        },
                        new
                        {
                            ProductSizeID = new Guid("5321ff0e-a903-43eb-a7ee-d028957ecd2f"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8"),
                            SizeID = new Guid("9d7ff143-3e26-40ae-ab00-2fead9950a03")
                        },
                        new
                        {
                            ProductSizeID = new Guid("a43dab53-24b4-4a57-9ffc-dc2857949a45"),
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad"),
                            SizeID = new Guid("9d7ff143-3e26-40ae-ab00-2fead9950a03")
                        },
                        new
                        {
                            ProductSizeID = new Guid("e62dcfa4-f657-4b3d-90c5-30360ead6da6"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c"),
                            SizeID = new Guid("9d7ff143-3e26-40ae-ab00-2fead9950a03")
                        },
                        new
                        {
                            ProductSizeID = new Guid("e69ed519-f2ae-471d-aaf6-b3ba7854726c"),
                            ProductID = new Guid("4592ed37-1361-4761-a3dd-3654670006ce"),
                            SizeID = new Guid("9d7ff143-3e26-40ae-ab00-2fead9950a03")
                        },
                        new
                        {
                            ProductSizeID = new Guid("bced1a79-d108-4ef0-a9aa-ead8eb626bcc"),
                            ProductID = new Guid("6724d1cf-0d30-4723-8f61-ddf0174df9f7"),
                            SizeID = new Guid("9d7ff143-3e26-40ae-ab00-2fead9950a03")
                        },
                        new
                        {
                            ProductSizeID = new Guid("7e794d08-1b06-42c9-80bc-708dbfd17df0"),
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379"),
                            SizeID = new Guid("737cec84-034f-4e2d-b5d0-23c6ee424c66")
                        },
                        new
                        {
                            ProductSizeID = new Guid("196fa013-9986-4fb4-a534-f3b68a2a1ec4"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f"),
                            SizeID = new Guid("737cec84-034f-4e2d-b5d0-23c6ee424c66")
                        },
                        new
                        {
                            ProductSizeID = new Guid("0e6fffb6-c960-485d-8dd4-494a725c22d9"),
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac"),
                            SizeID = new Guid("737cec84-034f-4e2d-b5d0-23c6ee424c66")
                        },
                        new
                        {
                            ProductSizeID = new Guid("5afc9cfa-a9ca-421f-a801-613be7c465e6"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5"),
                            SizeID = new Guid("737cec84-034f-4e2d-b5d0-23c6ee424c66")
                        },
                        new
                        {
                            ProductSizeID = new Guid("0cb7a02c-c2a9-4439-9440-f92cde485ce0"),
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254"),
                            SizeID = new Guid("737cec84-034f-4e2d-b5d0-23c6ee424c66")
                        },
                        new
                        {
                            ProductSizeID = new Guid("f1c05b05-85ef-47c3-879c-cb7bed01414a"),
                            ProductID = new Guid("209f2710-32b9-4fe7-9d04-470c931184a1"),
                            SizeID = new Guid("737cec84-034f-4e2d-b5d0-23c6ee424c66")
                        },
                        new
                        {
                            ProductSizeID = new Guid("023077e8-c586-43c0-9720-1246d8696c62"),
                            ProductID = new Guid("8c335be4-5cd9-4df0-8bc7-b6322ea41ec2"),
                            SizeID = new Guid("737cec84-034f-4e2d-b5d0-23c6ee424c66")
                        },
                        new
                        {
                            ProductSizeID = new Guid("ab41640b-ee82-4371-9693-b11855754b38"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8"),
                            SizeID = new Guid("737cec84-034f-4e2d-b5d0-23c6ee424c66")
                        },
                        new
                        {
                            ProductSizeID = new Guid("2bbad93b-5104-4bb8-b906-8560daff58cc"),
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad"),
                            SizeID = new Guid("737cec84-034f-4e2d-b5d0-23c6ee424c66")
                        },
                        new
                        {
                            ProductSizeID = new Guid("6265d988-99c4-479a-ae24-dacc2fd5af72"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c"),
                            SizeID = new Guid("737cec84-034f-4e2d-b5d0-23c6ee424c66")
                        },
                        new
                        {
                            ProductSizeID = new Guid("9afc2527-49fe-4105-80e5-02e6eaa48d28"),
                            ProductID = new Guid("4592ed37-1361-4761-a3dd-3654670006ce"),
                            SizeID = new Guid("737cec84-034f-4e2d-b5d0-23c6ee424c66")
                        },
                        new
                        {
                            ProductSizeID = new Guid("c353a507-be4e-4f3f-8cfd-643d28c67083"),
                            ProductID = new Guid("6724d1cf-0d30-4723-8f61-ddf0174df9f7"),
                            SizeID = new Guid("737cec84-034f-4e2d-b5d0-23c6ee424c66")
                        },
                        new
                        {
                            ProductSizeID = new Guid("0e12ebcc-df41-4d46-9694-2aa9d1e1d9a2"),
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379"),
                            SizeID = new Guid("d72207b4-36fc-49e0-a66a-a7fef8aff5de")
                        },
                        new
                        {
                            ProductSizeID = new Guid("4e7eb644-6dc8-4375-a7a5-501aabd166ce"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f"),
                            SizeID = new Guid("d72207b4-36fc-49e0-a66a-a7fef8aff5de")
                        },
                        new
                        {
                            ProductSizeID = new Guid("2bcf3bd9-7f47-46dc-98d7-2b49ad48ce59"),
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac"),
                            SizeID = new Guid("d72207b4-36fc-49e0-a66a-a7fef8aff5de")
                        },
                        new
                        {
                            ProductSizeID = new Guid("f823bfc2-9734-416b-9285-2847e6b7ab45"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5"),
                            SizeID = new Guid("d72207b4-36fc-49e0-a66a-a7fef8aff5de")
                        },
                        new
                        {
                            ProductSizeID = new Guid("0f63ac3f-7ec4-4f14-8cf9-07db98a3f16e"),
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254"),
                            SizeID = new Guid("d72207b4-36fc-49e0-a66a-a7fef8aff5de")
                        },
                        new
                        {
                            ProductSizeID = new Guid("5e46d98c-8ecd-4c7a-a871-27962c6cf68b"),
                            ProductID = new Guid("209f2710-32b9-4fe7-9d04-470c931184a1"),
                            SizeID = new Guid("d72207b4-36fc-49e0-a66a-a7fef8aff5de")
                        },
                        new
                        {
                            ProductSizeID = new Guid("299e5310-c184-45a6-ab4c-b2389c9cb048"),
                            ProductID = new Guid("8c335be4-5cd9-4df0-8bc7-b6322ea41ec2"),
                            SizeID = new Guid("d72207b4-36fc-49e0-a66a-a7fef8aff5de")
                        },
                        new
                        {
                            ProductSizeID = new Guid("cc1ba0ad-1cbe-49b3-9aae-a08a781cbee4"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8"),
                            SizeID = new Guid("d72207b4-36fc-49e0-a66a-a7fef8aff5de")
                        },
                        new
                        {
                            ProductSizeID = new Guid("8dd9c325-d3db-4c5d-92a3-ef9bfa6e2ab4"),
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad"),
                            SizeID = new Guid("d72207b4-36fc-49e0-a66a-a7fef8aff5de")
                        },
                        new
                        {
                            ProductSizeID = new Guid("d2cdbc11-9d56-46c3-9f87-8d1e168c28a2"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c"),
                            SizeID = new Guid("d72207b4-36fc-49e0-a66a-a7fef8aff5de")
                        },
                        new
                        {
                            ProductSizeID = new Guid("e5b70fe6-68bb-4bb3-abb7-96189d6d0d7e"),
                            ProductID = new Guid("4592ed37-1361-4761-a3dd-3654670006ce"),
                            SizeID = new Guid("d72207b4-36fc-49e0-a66a-a7fef8aff5de")
                        },
                        new
                        {
                            ProductSizeID = new Guid("7adf252c-3ab9-41d5-829a-289895b2312f"),
                            ProductID = new Guid("6724d1cf-0d30-4723-8f61-ddf0174df9f7"),
                            SizeID = new Guid("d72207b4-36fc-49e0-a66a-a7fef8aff5de")
                        },
                        new
                        {
                            ProductSizeID = new Guid("e0d208f2-5a17-46c7-a25f-33ef18956afd"),
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379"),
                            SizeID = new Guid("7a1f6254-c77c-4a22-86a9-a023b98dbdf8")
                        },
                        new
                        {
                            ProductSizeID = new Guid("3e04e19e-ee4d-48e0-8f5e-5f8bbbbdf188"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f"),
                            SizeID = new Guid("7a1f6254-c77c-4a22-86a9-a023b98dbdf8")
                        },
                        new
                        {
                            ProductSizeID = new Guid("b8928151-8650-48c8-b555-db16896987e6"),
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac"),
                            SizeID = new Guid("7a1f6254-c77c-4a22-86a9-a023b98dbdf8")
                        },
                        new
                        {
                            ProductSizeID = new Guid("c7ade8f7-b549-42ea-8abc-25ab3377b97d"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5"),
                            SizeID = new Guid("7a1f6254-c77c-4a22-86a9-a023b98dbdf8")
                        },
                        new
                        {
                            ProductSizeID = new Guid("cfeee698-5d82-41af-baa4-1a9678012960"),
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254"),
                            SizeID = new Guid("7a1f6254-c77c-4a22-86a9-a023b98dbdf8")
                        },
                        new
                        {
                            ProductSizeID = new Guid("38655183-ef26-4ba7-baa2-77344fc9998b"),
                            ProductID = new Guid("209f2710-32b9-4fe7-9d04-470c931184a1"),
                            SizeID = new Guid("7a1f6254-c77c-4a22-86a9-a023b98dbdf8")
                        },
                        new
                        {
                            ProductSizeID = new Guid("7df83db8-1c2a-4edc-b507-b11f8ac06dd2"),
                            ProductID = new Guid("8c335be4-5cd9-4df0-8bc7-b6322ea41ec2"),
                            SizeID = new Guid("7a1f6254-c77c-4a22-86a9-a023b98dbdf8")
                        },
                        new
                        {
                            ProductSizeID = new Guid("ca505716-b500-4f2e-abf1-c08089c3135e"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8"),
                            SizeID = new Guid("7a1f6254-c77c-4a22-86a9-a023b98dbdf8")
                        },
                        new
                        {
                            ProductSizeID = new Guid("7b16e71f-fbe7-4bbd-baf4-b559d782457c"),
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad"),
                            SizeID = new Guid("7a1f6254-c77c-4a22-86a9-a023b98dbdf8")
                        },
                        new
                        {
                            ProductSizeID = new Guid("e6c02027-ae2a-439f-822b-9d8bf89701f1"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c"),
                            SizeID = new Guid("7a1f6254-c77c-4a22-86a9-a023b98dbdf8")
                        },
                        new
                        {
                            ProductSizeID = new Guid("13593d8e-c80e-4042-8397-1f52929886fc"),
                            ProductID = new Guid("4592ed37-1361-4761-a3dd-3654670006ce"),
                            SizeID = new Guid("7a1f6254-c77c-4a22-86a9-a023b98dbdf8")
                        },
                        new
                        {
                            ProductSizeID = new Guid("621fbf7c-a485-4eea-939e-c1bea540ea36"),
                            ProductID = new Guid("6724d1cf-0d30-4723-8f61-ddf0174df9f7"),
                            SizeID = new Guid("7a1f6254-c77c-4a22-86a9-a023b98dbdf8")
                        });
                });

            modelBuilder.Entity("WebApi.Models.Entities.ProductTagEntity", b =>
                {
                    b.Property<Guid>("ProductTagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductTagID");

                    b.HasIndex("ProductID");

                    b.HasIndex("TagID");

                    b.ToTable("ProductTags");

                    b.HasData(
                        new
                        {
                            ProductTagID = new Guid("67d39af5-86c8-4ef6-a3f2-9779bcfe955d"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f"),
                            TagID = new Guid("4a3914f7-deb4-4265-b869-57cc712f6896")
                        },
                        new
                        {
                            ProductTagID = new Guid("612e3183-ef55-4d02-9292-fc19ed8d3b54"),
                            ProductID = new Guid("633328ef-6a33-44dc-88b2-934dc60a91ac"),
                            TagID = new Guid("4a3914f7-deb4-4265-b869-57cc712f6896")
                        },
                        new
                        {
                            ProductTagID = new Guid("9d278df9-583f-48ba-945c-b7ee9197d0e4"),
                            ProductID = new Guid("209f2710-32b9-4fe7-9d04-470c931184a1"),
                            TagID = new Guid("4a3914f7-deb4-4265-b869-57cc712f6896")
                        },
                        new
                        {
                            ProductTagID = new Guid("3efc876a-6fa6-42fb-ad5d-d186491d07be"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8"),
                            TagID = new Guid("4a3914f7-deb4-4265-b869-57cc712f6896")
                        },
                        new
                        {
                            ProductTagID = new Guid("b9e77881-62d9-4cab-b0e0-0a7d4887d49b"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8"),
                            TagID = new Guid("971bbffb-1719-4e6e-89da-9ab5ab77a287")
                        },
                        new
                        {
                            ProductTagID = new Guid("9ad59ca5-a28a-44bf-9a5e-0de86a9e547d"),
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad"),
                            TagID = new Guid("971bbffb-1719-4e6e-89da-9ab5ab77a287")
                        },
                        new
                        {
                            ProductTagID = new Guid("25b68507-9a88-41ff-a195-ed8b665afcb8"),
                            ProductID = new Guid("6724d1cf-0d30-4723-8f61-ddf0174df9f7"),
                            TagID = new Guid("971bbffb-1719-4e6e-89da-9ab5ab77a287")
                        },
                        new
                        {
                            ProductTagID = new Guid("a5529298-10c7-439e-b15d-38f78968ef32"),
                            ProductID = new Guid("ddb9e337-b2e4-41fa-a97e-33bb39cbe80f"),
                            TagID = new Guid("bafb4114-a474-42c4-8088-9b0002aae502")
                        },
                        new
                        {
                            ProductTagID = new Guid("60c3692e-b9f9-4333-9964-6705b0adfb7e"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5"),
                            TagID = new Guid("bafb4114-a474-42c4-8088-9b0002aae502")
                        },
                        new
                        {
                            ProductTagID = new Guid("4795dfb2-5aea-4d69-85de-b81fbc5450a6"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8"),
                            TagID = new Guid("bafb4114-a474-42c4-8088-9b0002aae502")
                        },
                        new
                        {
                            ProductTagID = new Guid("ce87c3d5-bbcf-4043-b73f-0469bec5202d"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c"),
                            TagID = new Guid("bafb4114-a474-42c4-8088-9b0002aae502")
                        },
                        new
                        {
                            ProductTagID = new Guid("5b811b47-832b-4959-83c2-9682aa55d174"),
                            ProductID = new Guid("4592ed37-1361-4761-a3dd-3654670006ce"),
                            TagID = new Guid("bafb4114-a474-42c4-8088-9b0002aae502")
                        },
                        new
                        {
                            ProductTagID = new Guid("9b3a45f9-c5c9-4d70-816b-67707d70e604"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8"),
                            TagID = new Guid("8a6c018f-6b1c-4bca-beac-85dc2249748d")
                        },
                        new
                        {
                            ProductTagID = new Guid("67273a8d-769d-477b-ab5f-fd2d1e992384"),
                            ProductID = new Guid("394fed41-77aa-4100-88a4-af5ba7ce87ad"),
                            TagID = new Guid("8a6c018f-6b1c-4bca-beac-85dc2249748d")
                        },
                        new
                        {
                            ProductTagID = new Guid("3840e5b7-4f3c-41c7-9242-b60635173c72"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c"),
                            TagID = new Guid("8a6c018f-6b1c-4bca-beac-85dc2249748d")
                        },
                        new
                        {
                            ProductTagID = new Guid("76607119-639d-4ca4-bafe-19f3b5ee07ed"),
                            ProductID = new Guid("3e70c707-aee2-404b-a2fc-95a2d2c8c1b5"),
                            TagID = new Guid("5f9499ee-8cdb-457a-b09d-95c5b84cb379")
                        },
                        new
                        {
                            ProductTagID = new Guid("b90d96c8-1c44-4719-9113-80520b9b0235"),
                            ProductID = new Guid("1f8ba608-64b7-46f5-9501-fe5d5c91dcc8"),
                            TagID = new Guid("5f9499ee-8cdb-457a-b09d-95c5b84cb379")
                        },
                        new
                        {
                            ProductTagID = new Guid("177f27be-fb6e-4210-9da3-e2ce16a9bf66"),
                            ProductID = new Guid("ec3981b0-c39f-4dfd-ad42-8ca675f8076c"),
                            TagID = new Guid("5f9499ee-8cdb-457a-b09d-95c5b84cb379")
                        },
                        new
                        {
                            ProductTagID = new Guid("9ccc26e7-9146-4431-b77a-f59ce81a0451"),
                            ProductID = new Guid("3e608840-6a94-476e-a147-50e3da35f379"),
                            TagID = new Guid("42ce8eb8-ba9f-4708-aac8-e2f8159bf9d3")
                        },
                        new
                        {
                            ProductTagID = new Guid("8887b8c3-4578-4f0a-9256-0b968edab788"),
                            ProductID = new Guid("e120bec8-c592-47be-98a8-9569bac3b254"),
                            TagID = new Guid("42ce8eb8-ba9f-4708-aac8-e2f8159bf9d3")
                        },
                        new
                        {
                            ProductTagID = new Guid("27709c29-26ca-4765-87d6-264b07b0d1cf"),
                            ProductID = new Guid("8c335be4-5cd9-4df0-8bc7-b6322ea41ec2"),
                            TagID = new Guid("42ce8eb8-ba9f-4708-aac8-e2f8159bf9d3")
                        });
                });

            modelBuilder.Entity("WebApi.Models.Entities.SizeEntity", b =>
                {
                    b.Property<Guid>("SizeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SizeID");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            SizeID = new Guid("462e8f20-0c38-4c39-b39e-b2d5d651b24e"),
                            SizeName = "xs"
                        },
                        new
                        {
                            SizeID = new Guid("9d7ff143-3e26-40ae-ab00-2fead9950a03"),
                            SizeName = "s"
                        },
                        new
                        {
                            SizeID = new Guid("737cec84-034f-4e2d-b5d0-23c6ee424c66"),
                            SizeName = "m"
                        },
                        new
                        {
                            SizeID = new Guid("d72207b4-36fc-49e0-a66a-a7fef8aff5de"),
                            SizeName = "l"
                        },
                        new
                        {
                            SizeID = new Guid("7a1f6254-c77c-4a22-86a9-a023b98dbdf8"),
                            SizeName = "xl"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Entities.TagEntity", b =>
                {
                    b.Property<Guid>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagID");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagID = new Guid("4a3914f7-deb4-4265-b869-57cc712f6896"),
                            TagName = "shirts"
                        },
                        new
                        {
                            TagID = new Guid("971bbffb-1719-4e6e-89da-9ab5ab77a287"),
                            TagName = "pants"
                        },
                        new
                        {
                            TagID = new Guid("bafb4114-a474-42c4-8088-9b0002aae502"),
                            TagName = "outdoors"
                        },
                        new
                        {
                            TagID = new Guid("8a6c018f-6b1c-4bca-beac-85dc2249748d"),
                            TagName = "sports"
                        },
                        new
                        {
                            TagID = new Guid("5f9499ee-8cdb-457a-b09d-95c5b84cb379"),
                            TagName = "shoes"
                        },
                        new
                        {
                            TagID = new Guid("42ce8eb8-ba9f-4708-aac8-e2f8159bf9d3"),
                            TagName = "dresses"
                        });
                });

            modelBuilder.Entity("WebApi.Models.Entities.CategoryTagEntity", b =>
                {
                    b.HasOne("WebApi.Models.Entities.CategoryEntity", "Category")
                        .WithMany("CategoryTags")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Entities.ProductEntity", null)
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductEntityProductID");

                    b.HasOne("WebApi.Models.Entities.TagEntity", "Tag")
                        .WithMany("CategoryTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WebApi.Models.Entities.ProductCategoryEntity", b =>
                {
                    b.HasOne("WebApi.Models.Entities.CategoryEntity", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Entities.ProductEntity", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApi.Models.Entities.ProductColorEntity", b =>
                {
                    b.HasOne("WebApi.Models.Entities.ColorEntity", "Color")
                        .WithMany("ProductColors")
                        .HasForeignKey("ColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Entities.ProductEntity", "Product")
                        .WithMany("ProductColors")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApi.Models.Entities.ProductImageEntity", b =>
                {
                    b.HasOne("WebApi.Models.Entities.ImageEntity", "Image")
                        .WithMany("ProductImages")
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Entities.ProductEntity", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApi.Models.Entities.ProductReviewEntity", b =>
                {
                    b.HasOne("WebApi.Models.Entities.ProductEntity", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApi.Models.Entities.ProductSizeEntity", b =>
                {
                    b.HasOne("WebApi.Models.Entities.ProductEntity", "Product")
                        .WithMany("ProductSizes")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Entities.SizeEntity", "Size")
                        .WithMany("ProductSizes")
                        .HasForeignKey("SizeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("WebApi.Models.Entities.ProductTagEntity", b =>
                {
                    b.HasOne("WebApi.Models.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.Entities.TagEntity", "Tag")
                        .WithMany()
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("WebApi.Models.Entities.CategoryEntity", b =>
                {
                    b.Navigation("CategoryTags");

                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("WebApi.Models.Entities.ColorEntity", b =>
                {
                    b.Navigation("ProductColors");
                });

            modelBuilder.Entity("WebApi.Models.Entities.ImageEntity", b =>
                {
                    b.Navigation("ProductImages");
                });

            modelBuilder.Entity("WebApi.Models.Entities.ProductEntity", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("ProductColors");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductReviews");

                    b.Navigation("ProductSizes");

                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("WebApi.Models.Entities.SizeEntity", b =>
                {
                    b.Navigation("ProductSizes");
                });

            modelBuilder.Entity("WebApi.Models.Entities.TagEntity", b =>
                {
                    b.Navigation("CategoryTags");
                });
#pragma warning restore 612, 618
        }
    }
}
